[package]
name = "obvious-druid-talk"
version = "0.1.0"
authors = ["Ankur Sethi <contact@ankursethi.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.4.0"
